### ISSUE TITLE
What for create an amazing crypt lib if the installation guide is SO poor!

### ISSUE THREAD

**Issue by huogerac** [kelektiv/node.bcrypt.js#456]
I'm terrible failing installing it on my ubuntu 12 Server. After struggling a lot, I installed it locally (in my ubuntu 16), however, I could not install it in my server.

As you guys created an incredible and useful tool, you should at least create a guidance for how to install in the most common S.O.

So, disappointed...
Anyway, I'm using another library which was much easier/simpler and pleasant to install.

bcrypt install tutorial #FAIL

**Comment by rickharrison** [comment]
@huogerac This was incredibly rude. This software is provided *FREE* and is incredibly useful. Tens of thousands of people install this everyday without complaining or insulting the author(s) of this library.

**Comment by huogerac** [comment]
Hey Guys, Hey @rickharrison 

I apologize, you're right, I was rude! which wasn't my goal, actually it was the opposite, my goal was push you to improve the docs to make bcrypt even better.
Sorry one more time! as I said before, the lib is amazing, I'm not complaining about bcrypt it self.

Just try to understand the side of the a developer that got frustrated trying to install a lib, visited a lot of posts with many solutions that didn't work out.
Indeed, there are a lot of people with the same problem, mainly because the tools is great! people want to use it! Just they're facing problem installing it.

I would be happy to contribute with some tutorial, I just couldn't make it work in my Ubuntu 12.04 server.

Best regards,

**Comment by Billy-** [comment]
@huogerac There's no install tutorial because, provided you have met the dependencies ([listed in the readme](https://github.com/kelektiv/node.bcrypt.js#dependencies)), then it should just be a case of running `npm install`. Not only is there no need for a tutorial for this, but all the information neccescary is listed in the readme.
If you have met all of these dependencies and are still experiencing issues, then please post the specifics of the issue.
