### ISSUE TITLE
Use Travis for building releases 

### ISSUE THREAD

**Issue by agathver** [kelektiv/node.bcrypt.js#470]
Installation on heroku and macOS is difficult because it needs a build toolkit. 

It is possible to use Travis to build and upload native modules for each of those platforms. Similarly appveyor can be configured to upload windows binaries. 

Will that be a good idea? I'm thinking of starting a PR on this.

**Comment by simlevesque** [comment]
It is a good idea. It would half my deployment time.

**Comment by lukeramsden** [comment]
When is this going to happen? I can't even get bcrypt working at all on my windows machine.

**Comment by teckays** [comment]
BUMP

**Comment by Agathver** [comment]
Need some help in this. Currently busy with exams

**Comment by Agathver** [comment]
Since Linux and OSX are the only possible options in Travis. A similar arrangement can be made in AppVeyor

**Comment by ratheous** [comment]
I've been dealing with the need to uninstall/reinstall bcrypt on every deployment, even when I build the library and commit node_modules on my target platform. 

I found that even when I did this, I would still encounter an error in some deployments, but running the NPM install again would fix the problem. The only resulting change according to git was two paths in the generated package.json: the last value of an array within another array named "_args" and a string value named "_where" will change based on the absolute path to my project when the install is run. I can patch this file on deployment, but it's awkward and hacky. Would implementing this new build process have any effect on my issue by any chance?

**Comment by Agathver** [comment]
If you are commiting the node_modules folder only to avoid compilation of *this* module on your deployment target, then it should help.

**Comment by ratheous** [comment]
I'm committing node_modules into a deployment branch to avoid compilation of _anything_ on the target system. It's just that bcrypt is the only thing preventing that from working correctly due to the fact that it depends on absolute path(s) residing in bcrypt's package.json which is generated on install/build. 

I'm hoping that the change you're making to the build process will mean that those absolute paths are no longer required for it to function, or at least that the paths can be relative so changing the deployment directory without rebuilding doesn't cause it to break.

**Comment by Agathver** [comment]
@ratheous In the module's source, there are no absolute paths. Changes to package.json and addition of absolute paths is a NPM specific behavior, I suggest to try out [yarn](https://yarnpkg.com). Also an added benefit of yarn is lockfiles for faster module resolution.

**Comment by ratheous** [comment]
@Agathver I understand that NPM supplies the paths, but it seems that only bcrypt is sensitive to them. At least it is the only package which I'm having trouble with in this way, but perhaps that's because it's the only non-native module that I'm using in this project.

I've tried yarn before and had problems with it but I'll give it another shot, thanks.

**Comment by defunctzombie** [comment]
Closing this issue in favor of the open PR (so discussion should continue there)

**Comment by gene1wood** [comment]
@defunctzombie are you referring [above](https://github.com/kelektiv/node.bcrypt.js/issues/470#issuecomment-280859090) to PR #483 or #489 (the PRs I see referenced in this issue) when you say discussion should continue in "the open PR"?
