### ISSUE TITLE
Password and hash does not match

### ISSUE THREAD

**Issue by worldsnas** [kelektiv/node.bcrypt.js#553]
everything works fine and compare func does the job.

yet on this occasion, it will return wrong result and says pass and hash do not match, I have tried my strings with online checkers like this one and its a pass there.

please tell me how to fix it. strangely the returned error is undefined.

password: T32NizM5593ecbdd5b7ae6045e7ebffc4c510975d663b99c4163905314cf28f06c24c4c172b27045d47031340ad1bfceaf944fdf96b0bc4b101c631c8cacbddf5000001fcfb363d829ffde9d4ad56ffa6e95e78c08ac1acT32NizM5comments{"rel_id":"11","page":"1","type":"game","per_page":"10"}T32NizM5

hash: $2a$04$xmgwC6HMDLcHSGJo8fv3UubxlEpDsCvVhtNC2bc6P.ABIc2xFjaKq

**Comment by agathver** [comment]
It's an implementation flaw of 2a hashes, which are not properly handled in the OpenBSD bcrypt (the one this library is built upon).

Support for 2b is in the works, see PR #549

**Comment by michalkvasnicak** [comment]
We have similar problem with this combination:

```
hash: $2y$13$imCVFU4/3lOVzogYnjKVcOnutdKmv5HtLPbM1ao54yQfJkvRSA4FS
password: rootroot
```

in this implementation, compare returns `false` but in [bcryptjs](https://www.npmjs.com/package/bcryptjs) it works as expected (returns `true`).

**Comment by agathver** [comment]
@michalkvasnicak We do not support $2y$, change the prefix to $2a$, it _might_ work

**Comment by Apke** [comment]
Hi, got the same Problem, but without > 255 Signs on PW.

Could it be that there is a component like time included?

It is always 8 Signs mixed between numbers and Uppercase chars. It is only a pre-authentication Token.

I not really develop that, so nothing else was changed, but the customer comes from time to time with the same bug, that the tokens doesn't work.

Last Year "2016-12-19 10:23:06" i fixed it with re-creating of that hash. The Hash was created half a year before that. On April 2017 i validatet that the hashes are working and the was a user misstake.

Today i got the same issue again and it looks like that i need to create all hashes again.
So it looks like that after 1/2 years it doesn't work anymore.

I really got a problem now, bec. i must tell them that all PW's doesn't work anymore since time "x" - weeks or month

Example:

Old - not valid hash
`
// generated code:  _bcrypt2.default.hashSync(password, _bcrypt2.default.genSaltSync(10))
// password
45BD844D
// stored hash
$2a$10$RVm8JGvcquLnIJgXQwT5jOUnAgcxv0LNR0ZB/jn3TkK.kM.3g1saa
`

New - valid hash (currently)
`
// generated code:  _bcrypt2.default.hashSync(password, _bcrypt2.default.genSaltSync(10))
// password
45BD844D
// stored hash
$2a$10$HYIdDOgaukAR5/F/XwQJwOfAmCv7Rgi7Adp4YTxDo8qWgfWvlgkzC
`

**Comment by agathver** [comment]
Definitely, the hashes will differ everytime you generate the hash. But it shouldn't become invalid after a specific length of time. 
Perhaps the code you use for validation has some bug. Could you post the part of it please?

**Comment by Apke** [comment]
Hi @agathver 

Thank you for your fast reply. You are right it must be a new hash on each generation, because of the random salt.

I need to apologize for my previews comment. I'am embrassed that i wrote it and missed some pre conditions. It is no Bug here.

I read much about the bcrypt hashing function, to understand how it works and what could be go wrong.
After the validation i looked in this library to find someone with same problem.

I know that some randomizers using the current timestamp to get a better result, so i thought maybe it could be somthing similar here. But this was stupid, the only way to get a side effect like my case is a randomizing at hash validation and this means a contradiction.

The problem which @worldsnas has is the only thing that could be happen and is a result of limitation.


My Bug is only a half implemented service, which writes through a model but validates through a external csv reader. So the generated hash is currently never validated.

Please accept my apologies for this mistake.

**Comment by agathver** [comment]
2b and 2y are now supported
