### ISSUE TITLE
Error after run in debug mode 

### ISSUE THREAD

**Issue by usama-ayub** [kelektiv/node.bcrypt.js#557]
![image](https://user-images.githubusercontent.com/12628874/33122462-1980e218-cf99-11e7-8490-ec522e0e6f00.png)

Operating System: Window 10 64bit
npm version: 5.5.1
node version: 6.11.3
bcrypt version: 1.0.3

**Comment by agathver** [comment]
It's clear. You compiled your module against an earlier version of NodeJS.
```
npm rebuild bcrypt
```
This should fix your issue

**Comment by lobosan** [comment]
The problem wasn't bcrypt but instead visual studio code debugger was detecting my system's node version which is v9.2.0
`Debugging with inspector protocol because Node.js v9.2.0 was detected.`

But I'm using nvm for my projects with version 8.9.1 so before opening vscode, I had to run these commands in my terminal

```
nvm use v8.9.1
code
```
Then I run the debugger and get the correct version detected.
`Debugging with inspector protocol because Node.js v8.9.1 was detected.`

Hope this helps someone in a similar situation
