### ISSUE TITLE
bcrypt does not work with Node 9.x

### ISSUE THREAD

**Issue by danielcasler** [kelektiv/node.bcrypt.js#558]
Bcrypt does not build with Node 9.x.  NPM produces the following errors:

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@9.1.0 (node-v59 ABI) (falling back to source compile with node-gyp)

**Comment by agathver** [comment]
We are unable to provide pre-built binaries since our CI are unable to compile for Node 9. We are waiting for npm to release a new version.

However, bcrypt itself compiles fine. You should install build-dependencies as mentioned here: https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by agathver** [comment]
@danielcasler  Binaries are available
