### ISSUE TITLE
Help with understanding the compatibility matrix

### ISSUE THREAD

**Issue by vichle** [kelektiv/node.bcrypt.js#739]
I have a library project that uses bcrypt as a dependency. This library has to support node v6. Is it possible to do this while also supporting Node v10? 

We are currently using bcrypt@1.0.3 on Node v6 and v8 but want to use v10 and soon v12 for new projects.

**Comment by YasharF** [comment]
Is there a specific question that you have regarding the table at https://github.com/kelektiv/node.bcrypt.js#version-compatibility

> ## Version Compatibility
> 
> | Node Version   | Bcrypt Version |
> | -------------- | -------------- |
> | 0.4            | <= 0.4         |
> | 0.6, 0.8, 0.10 | >= 0.5         |
> | 0.11           | >= 0.8         |
> | 4              | <= 2.1.0       |
> | 8              | >= 1.0.3       |
> | 10, 11         | >= 3           |
> | 12 (nightly)   | >= 3.0.6       |

**Comment by vichle** [comment]
There is no entry in the table for Node 6, hence the question. Sorry if it was unclear that I had already read the compatibility table.

**Comment by YasharF** [comment]
Node 6 is NODE_MODULE_VERSION v48, and the current releases include v48:
https://github.com/kelektiv/node.bcrypt.js/releases

Ref: https://nodejs.org/en/download/releases

You do have your requirement, but I would suggest talking to whoever set the requirement that since Node 6 is in EOL, it is a security risk by itself and needs to be upgraded to a newer version.
