### ISSUE TITLE
Bcrypt Compare failing with Node Alpine in Docker

### ISSUE THREAD

**Issue by MiKr13** [kelektiv/node.bcrypt.js#795]
Recently I changed my DockerFile `node:12.14.1` to `node:12.14.1-alpine`, after that bcrypt.compare started failing & it's crashing the server.
* This went wrong - bcrypt.compare not working with `node:12.14.1-alpine`
* This should happen? - Login should have proceeded, my code is alright: `const pwdPassed = await bcrypt.compare(password, user.pwdHash)`
* Version of nodejs and OS? 12.14.1, Docker with `node:12.14.1-alpine` as the base image and OS Windows which is irrelevant in case of Docker.

**Comment by MiKr13** [comment]
It is weird but after Docker restart it got solved.

**Comment by mtjn** [comment]
I also had this issue, and resolved it by restarting the docker service using `systemctl`

**Comment by yasser-mas** [comment]
Same issue here, even after restarting docker service

**Comment by Jobinjose01** [comment]
I know its old Post but the issue is using node Alpine docker I was using node:22-alpine I spent hours on it , finally found its due to alpine when I switch to node:22 image everything works without any issue :)

**Comment by sreyask555** [comment]
Yes, bcrypt will fail on alpine based node images.
The issue with bcrypt in Alpine-based images occurs because:

- Alpine Linux uses musl libc instead of glibc which is used in standard Linux distributions
- BCrypt requires native bindings that need to be compiled during installation

The compilation process in Alpine can be problematic because:

- It requires additional build tools (gcc, make, python)
- The musl libc can cause compatibility issues with some native Node.js modules
- The pre-built binaries that npm tries to use aren't compatible with Alpine's architecture

**Comment by sreyask555** [comment]
The issue with bcrypt in Alpine-based images occurs because:

- Alpine Linux uses musl libc instead of glibc which is used in standard Linux distributions
- BCrypt requires native bindings that need to be compiled during installation

The compilation process in Alpine can be problematic because:

- It requires additional build tools (gcc, make, python)
- The musl libc can cause compatibility issues with some native Node.js modules
- The pre-built binaries that npm tries to use aren't compatible with Alpine's architecture
